languageCode = "ja"
title = "ckazu.info"
baseURL = "http://ckazu.info/"
hasCJKLanguage = true
theme = "ckazu"

[taxonomies]
tag = "tags"
category = "categories"
series = "series"

[Params]
aboutme = "ckazu"
disqusShortname = "ckazuinfo"
