languageCode = "ja"
title = "What is an Information Architecture?"
baseURL = "http://www.ckazu.info/"
hasCJKLanguage = true
theme = "ckazu"

[taxonomies]
tag = "tags"
category = "categories"
series = "series"

[Params]
aboutme = "ckazu"
disqusShortname = "ckazuinfo"
